# Generated by Django 3.2.4 on 2021-09-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt', models.DateField()),
                ('links', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt', models.DateField()),
                ('links', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt', models.DateField()),
                ('links', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt', models.DateField()),
                ('links', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt', models.DateField()),
                ('links', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt', models.DateField()),
                ('links', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt', models.DateField()),
                ('links', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt', models.DateField()),
                ('links', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Toi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt', models.DateField()),
                ('links', models.CharField(max_length=500)),
            ],
        ),
    ]
