# Generated by Django 3.2.4 on 2021-09-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BExp',
            new_name='BrillExp',
        ),
        migrations.RenameModel(
            old_name='BL',
            new_name='BuisLine',
        ),
        migrations.RenameModel(
            old_name='ET',
            new_name='EcoTimes',
        ),
        migrations.RenameModel(
            old_name='FE',
            new_name='FinExp',
        ),
        migrations.RenameModel(
            old_name='TH',
            new_name='Hindu',
        ),
        migrations.RenameModel(
            old_name='HT',
            new_name='HinTim',
        ),
        migrations.RenameModel(
            old_name='IE',
            new_name='IndExp',
        ),
    ]
