# Generated by Django 3.2.4 on 2021-09-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_auto_20210904_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brillexp',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buisline',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ecotimes',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='finexp',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hindu',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hintim',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='indexp',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mint',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='toi',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
    ]
