# Generated by Django 3.2.4 on 2021-09-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_auto_20210904_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexp',
            name='name',
            field=models.CharField(default='Indian Express', max_length=100),
        ),
    ]
