# Generated by Django 3.2.4 on 2021-09-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_alter_indexp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brillexp',
            name='name',
            field=models.CharField(default="Brill's Express", max_length=100),
        ),
        migrations.AlterField(
            model_name='buisline',
            name='name',
            field=models.CharField(default='The Buisness Line', max_length=100),
        ),
        migrations.AlterField(
            model_name='ecotimes',
            name='name',
            field=models.CharField(default='The Economic Times', max_length=100),
        ),
        migrations.AlterField(
            model_name='finexp',
            name='name',
            field=models.CharField(default='The Financial Express', max_length=100),
        ),
        migrations.AlterField(
            model_name='hindu',
            name='name',
            field=models.CharField(default='The Hindu', max_length=100),
        ),
        migrations.AlterField(
            model_name='hintim',
            name='name',
            field=models.CharField(default='The Hindustan Times', max_length=100),
        ),
        migrations.AlterField(
            model_name='indexp',
            name='name',
            field=models.CharField(default='The Indian Express', max_length=100),
        ),
        migrations.AlterField(
            model_name='mint',
            name='name',
            field=models.CharField(default='The Mint', max_length=100),
        ),
        migrations.AlterField(
            model_name='toi',
            name='name',
            field=models.CharField(default='The Times Of India', max_length=100),
        ),
    ]
